### ISSUE TITLE
Text content did not match. Server: "xx's Blog" Client: "Nextein Starter Blog"

### ISSUE THREAD

**Issue by inevity** [elmasse/nextein-starter#4]
Only change the site.json in the nextein starter to xx's Blog to replace Nextein Starter Blog', and index.js then npm run dev. When refresh, the 'xx's Blog' flash and then show the "Nextein Starter Blog". Why?

**Comment by elmasse** [comment]
Hi @inevity I moved this issue into this repo.

I'm not able to reproduce the issue as you mentioned. What did you change on index.js? Do you have a repo I can clone to test?

Here is the screen-capture I just made with the latest code from this repo:

![kapture 2018-12-30 at 14 43 00](https://user-images.githubusercontent.com/223235/50549734-621d3680-0c41-11e9-8693-adddc16009e2.gif)
